//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A5_try2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string BookingId { get; set; }
        public string Tourist { get; set; }
        public string Package { get; set; }
        public string BookingDate { get; set; }
    
        public virtual Tourist Tourist1 { get; set; }
        public virtual Package Package1 { get; set; }
    }
}
